In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import Sequential, Model

h = [1,0,0,0]
e = [0,1,0,0]
l = [0,0,1,0]
o = [0,0,0,1]

In [2]:
x_data = np.array([[h]], dtype = np.float32)

hidden_size = 2
cell = layers.SimpleRNNCell(units = hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[-0.7411288  -0.50976276]]], shape: (1, 1, 2)
states: [[-0.7411288  -0.50976276]], shape: (1, 2)


In [3]:
x_data = np.array([[h,e,l,l,o]], dtype=np.float32)

rnn = layers.SimpleRNN(units = hidden_size, return_sequences=True, return_state = True)
outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4)
outputs: [[[ 0.6278271  -0.34878212]
  [ 0.5513888   0.21609156]
  [-0.13702387  0.7898285 ]
  [-0.77151895  0.8349598 ]
  [-0.54338354  0.72410166]]], shape: (1, 5, 2)
states: [[-0.54338354  0.72410166]], shape: (1, 2)


In [6]:
x_data = np.array([[h,e,l,l,o],
                   [e,o,l,l,l],
                   [l,l,e,e,l]], dtype = np.float32)

rnn = layers.SimpleRNN(units = hidden_size, return_sequences=True, return_state = True)
outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4)
outputs: [[[-0.19025883 -0.67460185]
  [-0.2870001   0.43448895]
  [-0.13534546 -0.4021823 ]
  [ 0.5957715  -0.2084294 ]
  [ 0.47661906 -0.88002574]]

 [[-0.67890304  0.008806  ]
  [-0.21187885 -0.30149943]
  [ 0.51021373 -0.18243681]
  [ 0.6405222  -0.7111959 ]
  [ 0.8600481  -0.65565974]]

 [[ 0.36162814 -0.4649671 ]
  [ 0.7410315  -0.56207955]
  [-0.00523956 -0.40254036]
  [-0.4334708   0.1810295 ]
  [ 0.03203463 -0.18453814]]], shape: (3, 5, 2)
states: [[ 0.47661906 -0.88002574]
 [ 0.8600481  -0.65565974]
 [ 0.03203463 -0.18453814]], shape: (3, 2)
